version: "3.9"

services:
  mysql:
    image: mysql:8.0
    container_name: mysql8
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    ports:
      - "3306:3306"
    volumes:
      - mysql8_data:/var/lib/mysql

  nestjs_be:
    build:
      context: ./node
    container_name: nestjs_be
    working_dir: /app
    volumes:
      - ../back_end:/app
    tty: true
    # command: ["sh", "-c" ,"bun install && npm run build && npm run start"]
    command: ["sh"]
    
    ports:
      - "3001:3001"
    depends_on:
      - mysql

  nextjs_fe:
    build:
      context: ./node
    container_name: nextjs_fe
    working_dir: /app
    volumes:
      - ../front_end:/app
    tty: true
    command: ["sh"]
    ports:
      - "3000:3000"

volumes:
  mysql8_data: